### ISSUE TITLE
[Feature Request]: Add forget password

### ISSUE THREAD

**Issue by mehul-m-prajapati** [kartikayasijaa/talk-trove#109]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

To allow user to reset his password if he/she forgets his password

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Sibam-Paul** [comment]
@mehul-m-prajapati how  is ur progress??

**Comment by mehul-m-prajapati** [comment]
@Sibam-Paul : suggest me which approach should I follow..
1. Sending otp
2. Sending reset link in email
3. Adding security questions in user profile

**Comment by Sibam-Paul** [comment]
1

**Comment by mehul-m-prajapati** [comment]
Services like SendGrid, Mailgun, or Amazon SES allow you to send emails without needing to expose your email credentials.

**SendGrid**:

- Sign up for a SendGrid account.
- Generate an API key in the SendGrid dashboard.
- Use the API key in your application instead of your email/password.
- Example with SendGrid:

```
const sgMail = require('@sendgrid/mail');
sgMail.setApiKey(process.env.SENDGRID_API_KEY);

const sendEmail = async (to, subject, text) => {
    const msg = {
        to,
        from: 'your-verified-email@example.com',
        subject,
        text,
    };
    await sgMail.send(msg);
};
```
@Sibam-Paul : Should I use SendGrid service ?

**Comment by Sibam-Paul** [comment]
@mehul-m-prajapati It's goin to take charge no.
And integrate the API key need to talk to @kartikayasija about the API key

**Comment by mehul-m-prajapati** [comment]
@Sibam-Paul : Closing issue because of long wait times.

**Comment by Sibam-Paul** [comment]
@mehul-m-prajapati Open it he was busy so couldn't reply
