### ISSUE TITLE
Script for adding dummy data

### ISSUE THREAD

**Issue by kartikayasijaa** [kartikayasijaa/talk-trove#11]
- write a script which will create dummy users, groups and chats
- As when locally deployed initially no users present to add to the group
![image](https://github.com/user-attachments/assets/115a9345-ad15-428e-ba42-499c0cc07358)

**Comment by priyanshuverma-dev** [comment]
May I work on this issue

**Comment by Sibam-Paul** [comment]
@priyanshuverma-dev I am assigning u this issue as I am been assigned Mentor to this Repo.
Go ahead can u attach a video at the end to confirm it's working when u give PR
