### ISSUE TITLE
[Feature Request]: sign up is not working 

### ISSUE THREAD

**Issue by Aditya90456** [kartikayasijaa/talk-trove#113]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

 
![Current situation of Sam and 2 more pages - Personal 2 - Microsoft​ Edge Beta 10_16_2024 6_12_52 PM](https://github.com/user-attachments/assets/a42cd20d-c5da-4aa9-a55c-9a6c5433992b)

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I want to work on this issue
- [ ] I'm willing to provide further clarification or assistance if needed.

**Comment by Sibam-Paul** [comment]
@Aditya90456 raise question in discussion tab

**Comment by Aditya90456** [comment]
loading

**Comment by Sibam-Paul** [comment]
duplicate issue #107

**Comment by Sibam-Paul** [comment]
already assigned
