### ISSUE TITLE
[Feature Request]: New And first time contributer 

### ISSUE THREAD

**Issue by sreehari20050** [kartikayasijaa/talk-trove#116]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

hi recently i got selected as first contibuter and waiting to get assign the projects

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I want to work on this issue
- [ ] I'm willing to provide further clarification or assistance if needed.

**Comment by Sibam-Paul** [comment]
@sreehari20050 If u are having problem can u join discord via mobile so that it will be easier for me to understand
