### ISSUE TITLE
[Feature Request]: Adding preview in links shared to chat with click property

### ISSUE THREAD

**Issue by yashksaini-coder** [kartikayasijaa/talk-trove#119]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The main problem is to make the links shared in the chat clickable and also preview it in the chat like discord or LinkedIn, twitter, Instagram platform does.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Sibam-Paul** [comment]
@yashksaini-coder are u working

**Comment by yashksaini-coder** [comment]
> @yashksaini-coder are u working

yes already done just checking the response
