### ISSUE TITLE
[Docs] - Add github workflows 

### ISSUE THREAD

**Issue by Sibam-Paul** [kartikayasijaa/talk-trove#12]
Make GitHub workflows for :
- autocomment-iss-close
- autocomment-iss-raise
- autocomment-pr-merge
- autocomment-pr-raise
- close-old-issue
- close-old-pr
- greetings

**Comment by ChampGupta** [comment]
I would like to contribute to this issue. Please consider my request and assign it ASAP.
Regards

**Comment by samyak-aditya** [comment]
Hey assign me this
