### ISSUE TITLE
[BUG]  group chat is not showing 

### ISSUE THREAD

**Issue by Aditya90456** [kartikayasijaa/talk-trove#129]
![Feature Request _ responsible feature · Issue #121 · kartikayasijaa_talk-trove and 4 more pages - Personal 2 - Microsoft​ Edge Beta 10_17_2024 9_01_32 PM](https://github.com/user-attachments/assets/0ff02898-f706-4fc7-89e4-05ca4c48e70e)
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Sibam-Paul** [comment]
U have to click it not a bug
