### ISSUE TITLE
[UI]-Adding Dark mode feature to the App 

### ISSUE THREAD

**Issue by ROHAN7051** [kartikayasijaa/talk-trove#13]
hi i want to work on the dark mode feature for the application

**Comment by Sibam-Paul** [comment]
@ROHAN7051 ok go ahead

**Comment by Sibam-Paul** [comment]
@ROHAN7051 please attach screenshot in your PR

**Comment by ROHAN7051** [comment]
Okay thanks

**Comment by Sibam-Paul** [comment]
@ROHAN7051 are u still on this issue??

**Comment by ROHAN7051** [comment]
Yes I am working on that

**Comment by Sibam-Paul** [comment]
@ROHAN7051 ok just wanna confirm

**Comment by Sibam-Paul** [comment]
@ROHAN7051 are u on it now orelse it will be closed due to inactivity

**Comment by ROHAN7051** [comment]
@Sibam-Paul  sorry for the delay the homepage is done but i am getting trouble in accessing the chatpage

**Comment by ROHAN7051** [comment]
@Sibam-Paul   so sorry for the late response homepage was done while ago but i am getting error in accessing the  chatpage also i dont have backend experience u can assign this to somebody else

**Comment by Sibam-Paul** [comment]
@ROHAN7051 ok
