### ISSUE TITLE
[BUG]: Guest user Credentials not working

### ISSUE THREAD

**Issue by Ahsankhalid618** [kartikayasijaa/talk-trove#131]
**Describe the bug**
Guest user credentials on the login page not working.

**Screenshots**
![image](https://github.com/user-attachments/assets/c8e50a8b-32f1-4526-839c-63025f953ff9)

**Desktop (please complete the following information):**
 - Windows: [e.g. Win 11]
 - Browser: Chrome

Assign me this issue and also add labels of hacktoberfest, gssoc-ext etc.

**Comment by Sibam-Paul** [comment]
Now it works see @Ahsankhalid618

**Comment by Ahsankhalid618** [comment]
Yup, Now it's working
