### ISSUE TITLE
[BUG] Old issue close

### ISSUE THREAD

**Issue by yashksaini-coder** [kartikayasijaa/talk-trove#138]
**Describe the bug**
The workflow only closes issues after 30 days timeline. 

**Expected behavior**
It should close issue after PR is merged

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Sibam-Paul** [comment]
@yashksaini-coder Go ahead submit it by tomorrow

**Comment by yashksaini-coder** [comment]
@Sibam-Paul please refer to the PR #152 I have raised it for `test` branch
