### ISSUE TITLE
[Feature Request]: Adding Contributors count with slideshow

### ISSUE THREAD

**Issue by yashksaini-coder** [kartikayasijaa/talk-trove#139]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Adding total contributors count with their proper slideshow.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Sibam-Paul** [comment]
@yashksaini-coder Go ahead submit it by tomorrow

**Comment by yashksaini-coder** [comment]
Im done just checking the code

**Comment by yashksaini-coder** [comment]
@Sibam-Paul check the PR
