### ISSUE TITLE
[Bug]: White page appears after sign up when the app is deployed 

### ISSUE THREAD

**Issue by Sibam-Paul** [kartikayasijaa/talk-trove#14]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened and Write Steps to Produce(ie. How u got the bug)?

When the app locally deployed after sign up , it becomes white

Steps to Produce : 
signup then when the app refresh it is navigated to /chats and below appears

### Add ScreenShots

![image](https://github.com/user-attachments/assets/71a1fa1f-f303-4838-b0ec-d8cc30903099)

### Record

- [ ] I agree to follow this project's Code of Conduct
- [ ] I want to work on this issue
- [ ] I'm willing to provide further clarification or assistance if needed.

**Comment by anjumnnit** [comment]
@Sibam-Paul I am willing to work on this project as I have previously worked on chat application so please assign this to me.

**Comment by kartikayasijaa** [comment]
Go for it @anjumnnit

**Comment by Sibam-Paul** [comment]
@anjumnnit This problem also occurs when deployed in vercel

**Comment by Sibam-Paul** [comment]
@anjumnnit Any progress

**Comment by Sibam-Paul** [comment]
closing not replying

**Comment by anjumnnit** [comment]
> closing not replying

Ya you can assign it to someone else as I am not able to figure out the problem.
