### ISSUE TITLE
[Feature Request]: ADD FEATURES SECTION ON README FILE

### ISSUE THREAD

**Issue by alo7lika** [kartikayasijaa/talk-trove#150]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Adding a Feature section to the README file serves several important purposes:

1. Improves Clarity for Users:
It clearly explains what the project offers and helps users quickly understand the functionality of the application.
By listing features, it sets expectations for users, so they know what capabilities they can expect when using the app.
2. Attracts Contributors:
Detailed feature descriptions help potential contributors grasp the scope of the project and identify areas where they might want to contribute.
It also helps them see what’s already implemented, preventing duplicate efforts.
3. Showcases the App’s Value:
Highlighting key features demonstrates the usefulness and uniqueness of the app.
It serves as a selling point for people considering using or supporting the project, motivating them to engage with it.
4. Helps with Maintenance and Documentation:
For future developers, it’s a useful reference to understand the capabilities of the app at a glance.
It documents the evolution of the project, making it easier to track the implementation of new features and improvements over time.
5. Enhances Discoverability:
Features sections can make the project more appealing in open-source communities, attracting more attention from developers and users. This can lead to more stars, forks, and contributions.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by alo7lika** [comment]
ADD GSSOC AND HACKTOBERFEST LABELS AND ASSIGN ME THIS WORK @kartikayasijaa

**Comment by Sibam-Paul** [comment]
@alo7lika Just tell me what u will update

**Comment by alo7lika** [comment]
> @alo7lika Just tell me what u will update

The addition of a Features section to the README file section will provide a comprehensive overview of the capabilities offered by Chat App.

Why This Matters
By detailing the features, I aim to give users and contributors a clearer understanding of what app provides. Here’s a sneak peek of some of the features that will be included:

- Real-Time Messaging: Experience instant communication with users through WebSockets.
- User Authentication: Secure sign-up and login with encrypted passwords.
- Private and Group Chats: Engage in one-on-one conversations or create group discussions.
- File Sharing: Send images and documents directly within the chat.
- Responsive Design: Access the app seamlessly on both desktop and mobile devices.

**Comment by Sibam-Paul** [comment]
@alo7lika I don't think we need this update as the latest readme hold best to understand the project

**Comment by Sibam-Paul** [comment]
@alo7lika Try to find bugs or add features instead of readme

**Comment by Sibam-Paul** [comment]
Close it
