### ISSUE TITLE
[DOC] Addition of All Contributors Photos in Readme | Readme Updation

### ISSUE THREAD

**Issue by Shariq2003** [kartikayasijaa/talk-trove#19]
## Description
We can add all the contributor's photos in Readme file as a token of appreciation for their work.

Please assign this to me.

**Affected Pages**:
- [X] README.md
- [ ] Installation Guide
- [ ] Configuration Guide
- [ ] Other (please specify)

## Type of Documentation Change

- [X] Update existing documentation
- [ ] Add new documentation
- [ ] Remove outdated or redundant documentation
- [ ] Other (please specify)

## Additional Context
Like this
![image](https://github.com/user-attachments/assets/28b87774-1710-4842-8278-99f26c26e13b)

@Sibam-Paul please assign this to me.

**Comment by Sibam-Paul** [comment]
@Shariq2003 first complete #15 then I will assign u

**Comment by Shariq2003** [comment]
> @Shariq2003 first complete #15 then I will assign u

@Sibam-Paul sir, I am just looking for a good design for #15, meanwhile u can assign this issue to me and I will complete this within 1hrs after that I can work on #15

**Comment by Sibam-Paul** [comment]
@Shariq2003 Bro start working on the design

**Comment by Shariq2003** [comment]
> @Shariq2003 Bro start working on the design

okay bro
