### ISSUE TITLE
[Feature Request]: Improve Responsiveness for mobile users

### ISSUE THREAD

**Issue by rishabhrawat05** [kartikayasijaa/talk-trove#21]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Hi! @kartikayasija 
The app needs to be responsive so that mobile users can easily use the app

Here is the screenshot of how it looks now 
![Screenshot_2024_1005_213822](https://github.com/user-attachments/assets/613b0d72-9d07-49da-b92d-6be03449f813)

Please assign this issue to me 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by KiranBaliga** [comment]
@rishabhrawat05 please tag @kartikayasija (owner of the repo)

**Comment by rishabhrawat05** [comment]
> @rishabhrawat05 please tag @kartikayasija (owner of the repo)

Oh!  I am really sorry

**Comment by Sawan-Kushwah** [comment]
@kartikayasija can you please assign me this i want to work on this

**Comment by Sibam-Paul** [comment]
@rishabhrawat05 I am mentor of this repo please proceed solving the issue.

**Comment by Sibam-Paul** [comment]
@Sawan-Kushwah try to take unassigned issue or make ur own issue I will assign u as fcfs is followed, if the person is inactive then only I will assign the next person

**Comment by rishabhrawat05** [comment]
Hey! @Sibam-Paul 
The responsiveness of app which was assigned to me is already been fixed by someone else ,so what should i do now
