### ISSUE TITLE
[Feature]: Dark theme for the site

### ISSUE THREAD

**Issue by ayush-badola** [kartikayasijaa/talk-trove#27]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The site will have a toggle option for light theme and dark theme. Light theme will be default, which could be changed by clicking on the dark theme button.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by ayush-badola** [comment]
I want to work on this feature. Please assign it to me, under GSSoC Extended and Hactoberfest 2024.
Thanks!

**Comment by Sibam-Paul** [comment]
@ayush-badola Go ahead please attach ss or short video on PR

**Comment by Sibam-Paul** [comment]
@ayush-badola it's duplicate bro see issue #13

**Comment by Sibam-Paul** [comment]
@ayush-badola raise other issue I will assign u but see if it's not the same issue u are raising

**Comment by Sibam-Paul** [comment]
Closing it duplicate

**Comment by Sibam-Paul** [comment]
@ayush-badola I will open it and assign u if the contributor who mentioned the issue is inactive
