### ISSUE TITLE
[UI]: Chat App UI Not Responsive on Mobile Devices

### ISSUE THREAD

**Issue by RaiDevX8** [kartikayasijaa/talk-trove#28]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description
@kartikayasijaa @Shivam-Pathak-22 @2003mahi
The chat app's user interface is not responsive when viewed on mobile devices. The layout does not adjust properly, making it difficult for users to interact with the app.
![Screenshot 2024-10-06 181455](https://github.com/user-attachments/assets/fb2e1be7-c458-4128-83a9-3a1abcc2eb97)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Sibam-Paul** [comment]
@RaiDevX8 I am mentor here of this repo Go head do it
