### ISSUE TITLE
Add Code of Conduct

### ISSUE THREAD

**Issue by KiranBaliga** [kartikayasijaa/talk-trove#3]
Hey 🥳! I see that repository is missing code of conduct. I would like to add a code of conduct developed from scratch for your project. Please let me know if it is okay to proceed. Please assign to me and add GSSoC24 Ext & level1 Labels.

**Comment by Sibam-Paul** [comment]
@KiranBaliga  I am mentor of this repo try to raise issues , after get response from the PA , I will assign it

**Comment by Sibam-Paul** [comment]
@KiranBaliga Already done raise issue by reading the Readme file to setup locally

**Comment by Sibam-Paul** [comment]
Closing
