### ISSUE TITLE
[Feature Request]: send button and emoji feature missing

### ISSUE THREAD

**Issue by geetanjalidubey9** [kartikayasijaa/talk-trove#33]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I saw the chat part there is no feature like adding emoji and a send  button 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by NilanchalaPanda** [comment]
Hey @kartikayasija, can I work on this issue if @geetanjalidubey9 is not working upon it.

**Comment by Sibam-Paul** [comment]
@geetanjalidubey9 Hey won't u be working on it or shall I assign the next ???

**Comment by geetanjalidubey9** [comment]
i am working on it

**Comment by Sibam-Paul** [comment]
Ok
