### ISSUE TITLE
[BUG] Sign Up Pages Improvement Needed

### ISSUE THREAD

**Issue by 4F24L** [kartikayasijaa/talk-trove#34]
**Describe the bug**
-- Sign Up / Login page should be improved.

**To Reproduce**
1. Go to https://chat-app-two-theta-52.vercel.app/
2. See error

**Expected behavior**
- Sign Up Page Improvement Needed

**Screenshots**
![image](https://github.com/user-attachments/assets/925ea9c7-a133-40d9-8d8f-4e83006d95e5)

**Desktop (please complete the following information):**
 - OS: WIN
 - Browser : Chrome
 - Version : Latest

**Additional context**

**Comment by Sibam-Paul** [comment]
@4F24L how far is ur progress
