### ISSUE TITLE
[Feature Request]: Encrypt Passwords Before Storing Them

### ISSUE THREAD

**Issue by iamsohelx** [kartikayasijaa/talk-trove#35]
### Is there an existing issue for this?

- [X] I have searched the existing issues

## Description
Hey @kartikayasija In your website you are directly storing users password without encrypting it first.
This would an serious issue because users data is not secure.
anyone can see their passwords.

## Screenshot
![Hash6](https://github.com/user-attachments/assets/e2a89a55-5f48-4f67-88fc-9368672bbf18)

## Solution
I can fix this issue by encrypting the password before storing it in database.
using Bcrypt, it will make your platform more secure.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by iamsohelx** [comment]
Hey @kartikayasija i can help you to fix this issue and make your platform more secure, could you please assign this task to me

**Comment by Sibam-Paul** [comment]
And @iamsohelx please mention in detail I mean the path of the file where u find the bug easier to clarify it

**Comment by iamsohelx** [comment]
> @iamsohelx have u checked the models there is a function to encrypt it

Ohh my mistake 🙇🏻 I haven't seen this
