### ISSUE TITLE
[Feature Request] : Background in Landing Page and Improve the form UI 

### ISSUE THREAD

**Issue by anmol-284** [kartikayasijaa/talk-trove#36]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

want to add Background in Landing Page and making the UI of form more Animated.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Sibam-Paul** [comment]
What landing page bro Gimme ss can't understand

**Comment by anmol-284** [comment]
![Screenshot 2024-10-07 212858](https://github.com/user-attachments/assets/88278638-484d-495d-8465-766488401db8)
![Screenshot 2024-10-07 213021](https://github.com/user-attachments/assets/6cf3e767-084f-4caf-8dc8-9346fe15dd6f)
Something from these types of backgrounds can be added in the main page

**Comment by Sibam-Paul** [comment]
Go @anmol-284

**Comment by Sibam-Paul** [comment]
Give some animation but don't make the website slow

**Comment by anmol-284** [comment]
Yeah i take care of it

**Comment by Sibam-Paul** [comment]
If u have any problem please open a question/answer tab in the discussion section of this repo plz it would be helpful 
and always look at it for announcement plz of any changes we will make regarding issues

**Comment by Sibam-Paul** [comment]
@anmol-284 Please see the discussion tab and join discord plz
