### ISSUE TITLE
[DOC]-Add Github Greeting Bot

### ISSUE THREAD

**Issue by KiranBaliga** [kartikayasijaa/talk-trove#4]
Hey 🥳 Looks like an amazing project idea! I see this repo lacks a small enhancement Github Greetings bot that sends auto messages to greet new users when they raise a PR or an issue. Let me know if you would like this level1 set up! Please assign to me if interested! (GSSoC24 Contribution)

**Comment by Sibam-Paul** [comment]
@KiranBaliga  I am mentor of this repo try to raise issues , after get response from the PA , I will assign it

**Comment by Sibam-Paul** [comment]
@KiranBaliga Do ahead and make it quick

**Comment by KiranBaliga** [comment]
@Sibam-Paul I have raised the PR..Please review. Thank you!
