### ISSUE TITLE
[Feature Request]: Mute notifications for chat

### ISSUE THREAD

**Issue by meghanakn473** [kartikayasijaa/talk-trove#40]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Muting notifications for particular chat helps the user not to get disturbed from the messages in group chat during their office time.
@kartikayasijaa please assign me this issue 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by kartikayasijaa** [comment]
Go ahead @meghanakn473

**Comment by meghanakn473** [comment]
@kartikayasijaa please assign me the labels level 3, gssoc-extd, hacktoberfest

**Comment by meghanakn473** [comment]
@Sibam-Paul @kartikayasijaa can u please help me out to fix this error
![image](https://github.com/user-attachments/assets/8e4990fc-fb36-4590-880d-0b67abb8afee)

wen ever i click on new chat group we i enter members of group and click on create this error is ocurring....and due to this im not able verify and check if mutong and un muting chats feature that i wanted to add is working or not

**Comment by Sibam-Paul** [comment]
@meghanakn473 can u come to discord ex-projecf-intro channel  tomorrow morning I will see it

**Comment by meghanakn473** [comment]
> @meghanakn473 can u come to discord ex-projecf-intro channel tomorrow morning I will see it

Sure can u share the discord link? @Sibam-Paul @kartikayasijaa

**Comment by meghanakn473** [comment]
> > @meghanakn473 can u come to discord ex-projecf-intro channel tomorrow morning I will see it
> 
> Sure can u share the discord link? @Sibam-Paul @kartikayasijaa

@kartikayasijaa ??

**Comment by meghanakn473** [comment]
> @meghanakn473 can u come to discord ex-projecf-intro channel  tomorrow morning I will see it

Please tell me discord username so that I can fix the issue
I have spent time on working this issue
I Hooe you'll consider it

@Sibam-Paul @kartikayasijaa

**Comment by kartikayasijaa** [comment]
messaged you on linkedin
