### ISSUE TITLE
[Feature Request]: Landing Page for the application.

### ISSUE THREAD

**Issue by NilanchalaPanda** [kartikayasijaa/talk-trove#42]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

- A simple Home Page for the application. Currently the auth page is display as the Landing Page.
- GSOC-EXT '24.
- Hacktoberfest

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by kartikayasijaa** [comment]
We don't want a landing page for this project.

**Comment by NilanchalaPanda** [comment]
Okay @kartikayasijaa, no issues.
