### ISSUE TITLE
[Enhancement] - Changing the UI of Login 

### ISSUE THREAD

**Issue by T-Rahul-prabhu-38** [kartikayasijaa/talk-trove#5]
can u assgin me this so i can refactor the UI  for login and signup.

**Comment by Sibam-Paul** [comment]
@T-Rahul-prabhu-38  I am mentor of this repo try to raise issues , after get response from the PA , I will assign it

**Comment by T-Rahul-prabhu-38** [comment]
im new here what/who is PA

**Comment by Sibam-Paul** [comment]
@T-Rahul-prabhu-38 Change the UI of Login Go ahead

**Comment by Sibam-Paul** [comment]
@T-Rahul-prabhu-38 Hey any update ???

**Comment by T-Rahul-prabhu-38** [comment]
working on it , will push a PR in few mins.

**Comment by Sibam-Paul** [comment]
@T-Rahul-prabhu-38 Any update

**Comment by Sibam-Paul** [comment]
Closing due to inactive
