### ISSUE TITLE
[Feature Request]: Make the Profile more appealing. 

### ISSUE THREAD

**Issue by NilanchalaPanda** [kartikayasijaa/talk-trove#50]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

- Currently the profile card only displays the email of the user.
- We can add username and other details as well improve the UI of the card.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Sibam-Paul** [comment]
@NilanchalaPanda same issue #23 please verify

**Comment by Sibam-Paul** [comment]
closing
