### ISSUE TITLE
[Feature Request]: Add Multilingual Support to the Application

### ISSUE THREAD

**Issue by IkkiOcean** [kartikayasijaa/talk-trove#51]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The application currently supports only one language, which limits its accessibility to users from different linguistic backgrounds. To improve the user experience and make the app more inclusive, we need to add support for multiple languages. The goal is to enable users to switch between languages seamlessly, ensuring that all content is translated accurately across the application.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Sibam-Paul** [comment]
@IkkiOcean we don't need rn but good issue raised

**Comment by Sibam-Paul** [comment]
@kartikayasijaa @kartikayasija  do we need this rn ??

**Comment by IkkiOcean** [comment]
It will be an add-on feature which will increase its user base as users with different language origin can interact.

**Comment by Sibam-Paul** [comment]
@IkkiOcean yup

**Comment by Sibam-Paul** [comment]
closing not requiring this functionality
