### ISSUE TITLE
Add a custom favicon 

### ISSUE THREAD

**Issue by AyushSharma72** [kartikayasijaa/talk-trove#53]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

i want to add a custom favicon to the website 

![image](https://github.com/user-attachments/assets/e3376690-e243-4713-9d2a-a545a277aee0)

please assign this issue to me @ka

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Sibam-Paul** [comment]
@AyushSharma72
