### ISSUE TITLE
[BUG]: Unknown error while logging in with guest credentials

### ISSUE THREAD

**Issue by bj-jiwrajka** [kartikayasijaa/talk-trove#57]
![image](https://github.com/user-attachments/assets/59b31e2c-9a2c-4b0c-bbc1-27f1365619d4)

**Comment by Sachita007** [comment]
I want to work on this issue

**Comment by bj-jiwrajka** [comment]
I'm working on it

**Comment by Sibam-Paul** [comment]
@bj-jiwrajka please tell me are u working on it

**Comment by Sibam-Paul** [comment]
Closing as not replying
