### ISSUE TITLE
[UI]- Remove react favicon 

### ISSUE THREAD

**Issue by sh78ba** [kartikayasijaa/talk-trove#6]
remove the react favicon 
<img width="1440" alt="Screenshot 2024-10-02 at 9 12 00 PM" src="https://github.com/user-attachments/assets/bbfe541c-b671-40b9-90b8-d96c0f3a2a52">

**Comment by fawad-10** [comment]
I would like to do contribute in this issue, do assign me.

**Comment by Sibam-Paul** [comment]
@sh78ba I am mentor of this repo try to raise issues , after get response from the PA , I will assign it

**Comment by Sibam-Paul** [comment]
@fawad-10 try raising issues for now . it will take time to assign u guys

**Comment by Sibam-Paul** [comment]
@fawad-10 Go ahead and show me the new favicon

**Comment by Sibam-Paul** [comment]
@fawad-10 Any update??

**Comment by Abheeshta-P** [comment]
Is it finished?? I would like to work on it!

**Comment by Abheeshta-P** [comment]
@Sibam-Paul  Thanks for assigning could you please let me know is there is any particular logo for this project so hat i can put in there??

**Comment by Sibam-Paul** [comment]
@fawad-10 Please see discussion tab and join discord plz
