### ISSUE TITLE
[Feature Request]: Trigger Login/Register button automatically on enter

### ISSUE THREAD

**Issue by bj-jiwrajka** [kartikayasijaa/talk-trove#60]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

This feature suggests automatic trigger of login/signup button on enter button

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Sibam-Paul** [comment]
@bj-jiwrajka Explain bro can't understand

**Comment by Sibam-Paul** [comment]
@bj-jiwrajka Closing not responsing
