### ISSUE TITLE
[DOC] : Make a sample env file

### ISSUE THREAD

**Issue by bj-jiwrajka** [kartikayasijaa/talk-trove#61]
## Description

Make a  ```.env.sample``` file for developers' convenience.

**Affected Pages**:
- [x] README.md

## Type of Documentation Change

- [x] Update existing documentation
- [x] Add new documentation
- [ ] Remove outdated or redundant documentation
- [ ] Other (please specify)

**Comment by bj-jiwrajka** [comment]
Hey @kartikayasijaa @Sibam-Paul , can I do this small but important change?

**Comment by Sibam-Paul** [comment]
@bj-jiwrajka ok make it although to make a env file is there in the readme also change the readme according to it

**Comment by bj-jiwrajka** [comment]
> @bj-jiwrajka ok make it although to make a env file is there in the readme also change the readme according to it

yeah sure. I am going to update the readme file too as mentioned in the issue description. In the mean time, can you please assign it to me and add the labels of hactoberfest etc.?
