### ISSUE TITLE
[DOC] Add Metrics Table to README

### ISSUE THREAD

**Issue by neeru24** [kartikayasijaa/talk-trove#66]
### Issue: Add Metrics Table to README

It would enhance the README file significantly to include a table displaying key repository metrics such as the number of stars, forks, pull requests, and any other relevant statistics. This addition will make the repository more informative and visually appealing to users.

**Benefits:**

- Improves the overall presentation of the README.
- Encourages contributions by showcasing community involvement.

**Comment by yashksaini-coder** [comment]
@neeru24 can you provide screenshots of these Metrics table

**Comment by neeru24** [comment]
> @neeru24 can you provide screenshots of these Metrics table

![image](https://github.com/user-attachments/assets/bbb0da94-4c18-4f24-997d-bbf4e741b3e3)
 something like this..
It's screenshot from my previous work

**Comment by yashksaini-coder** [comment]
okh looks good, how did you come up with this design

**Comment by neeru24** [comment]
> okh looks good, how did you come up with this design

just while exploring and some idea from other similar designs...

can you assign me this

**Comment by yashksaini-coder** [comment]
No i am a contributor like you new to open source so just seeing what other ideas are there,
currently learning react

**Comment by Sibam-Paul** [comment]
@neeru24 Go ahead
