### ISSUE TITLE
[Feature Request]:  Add Message Reactions to Chat

### ISSUE THREAD

**Issue by muskan171105** [kartikayasijaa/talk-trove#67]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I would like to propose adding a message reactions feature to the chat app. This would allow users to react to individual messages using emojis

**Benefits:**

-Enhances user engagement.
-Provides a quick way to express feedback.

Please mention this under gssoc and hacktoberfest

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by kartikayasijaa** [comment]
Go ahead @muskan171105

**Comment by muskan171105** [comment]
please add GssoC and Hacktoberfest labels for this issue
