### ISSUE TITLE
[Feature Request]: adding forget password functionality in project

### ISSUE THREAD

**Issue by zakie2003** [kartikayasijaa/talk-trove#71]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The login page can have a forget password functionality please assgin me under gssoc and hacktober fest

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Sibam-Paul** [comment]
duplicate #2
