### ISSUE TITLE
[Feature Request]: Add AI bot

### ISSUE THREAD

**Issue by yashksaini-coder** [kartikayasijaa/talk-trove#72]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

To add a simple AI bot with a zeroshot template in the chat application

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by yashksaini-coder** [comment]
@kartikayasijaa can you assign me this issue & add `gssoc-ext` & `hacktoberfest-accepted` labels to it.

**Comment by kartikayasijaa** [comment]
We don't need a bot.
