### ISSUE TITLE
[Feature Request]: Dark Mode

### ISSUE THREAD

**Issue by SudhanshuShekhar28** [kartikayasijaa/talk-trove#87]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Implementation of dark mode

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by SudhanshuShekhar28** [comment]
can you assigned to me

**Comment by Sibam-Paul** [comment]
#13 similar issue make @SudhanshuShekhar28

**Comment by Sibam-Paul** [comment]
@SudhanshuShekhar28 I will open it and assign u if the contributor who mentioned the issue is inactive
