### ISSUE TITLE
[Feature Request]: Enhancement of UI | Issues #1 Ref Issue #15

### ISSUE THREAD

**Issue by Shariq2003** [kartikayasijaa/talk-trove#94]
### Is there an existing issue for this?

Ref : Issue #15 

- [X] I have searched the existing issues

### Feature Description

1. Enhancement of Chat Header.
2. Enhancement of Chat Container.

From this 
![image](https://github.com/user-attachments/assets/87c850c2-3295-47e4-b461-491185e2c608)

To this
![image](https://github.com/user-attachments/assets/f37834e7-e7a0-4f2f-82fb-a3696baeb2ee)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Sibam-Paul** [comment]
link issue #15

**Comment by Shariq2003** [comment]
> link issue #15

See Title

**Comment by Sibam-Paul** [comment]
Are u using chakra UI as this repo is using it
