### ISSUE TITLE
the "chat" text not look attractive !

### ISSUE THREAD

**Issue by 2004pra** [kartikayasijaa/talk-trove#97]
as i am sharing you the screenshot of your website i want to change the look of text "chat:"
please assign me this task i will make sure to make the text look good and aesthetic
assign under gssocextd24, hacktoberfest
@kartikayasija 
![Screenshot 2024-10-14 201704](https://github.com/user-attachments/assets/d4b40079-ad1c-4a9e-98f6-2b5f3c8e3d3e)

**Comment by Sibam-Paul** [comment]
See discussion and join discord

**Comment by Sibam-Paul** [comment]
@2004pra please tell what u will change ???

**Comment by Sibam-Paul** [comment]
Join discord

**Comment by 2004pra** [comment]
i dont see the link in discussion section 
can  you share here

**Comment by Sibam-Paul** [comment]
Go to gssoc channel and under ext-project-intro search Talk-Trove and join it

**Comment by 2004pra** [comment]
i joined it

**Comment by 2004pra** [comment]
sorry i am closing this one
as i told you on discord
